### PR TITLE
Some changes to get ncollide working with Rust 1.0.0.beta4

### PR DESCRIPTION
**Pull request by tinco**
This is not the full set yet, I'm currently stuck on:

```
ncollide_utils/optimization.rs:174:39: 174:46 error: cannot apply unary operator `-` to type `V`
ncollide_utils/optimization.rs:174         let mut search_dir = hx.rmul(&-new_dx);
                                                                         ^~~~~~~
ncollide_utils/optimization.rs:179:26: 179:33 error: cannot apply unary operator `-` to type `V`
ncollide_utils/optimization.rs:179             search_dir = -new_dx;
                                                            ^~~~~~~
ncollide_utils/any_private.rs:13:9: 13:24 error: the trait `core::marker::Reflect` is not implemented for the type `T` [E0277]
ncollide_utils/any_private.rs:13         TypeId::of::<T>()
                                         ^~~~~~~~~~~~~~~
ncollide_utils/cov.rs:55:38: 55:55 error: cannot apply unary operator `-` to type `V`
ncollide_utils/cov.rs:55                 *pt = icov * (*pt + (-*center.as_vec()));

```

### CODE REVIEW

**Comment by sebcrozet** [comment]
Thanks for your work so far. I believe you figured out why the `-` operator was not found (cf. nalgebra#125). For the error related to `TypeId`, you might just have to add the `core::maker::Reflect` trait bound to `T`.

Though, I think that you probably should not pursue your work before the 1.0 rust compiler is released (next week IIRC). Currently, a clean fix of ncollide compilation problems require associated types, which still ICE when I try to use them (see #72). If the 1.0 version still ICEs, then we will have to find an alternative to associated types (which migh tbe the `PhantomData`) in order to remove `#[old_impl_check]`.

**Comment by tinco** [comment]
Hi, my e-mail notifications broke so I didn't see you had already responded. I'm just messing about learning Rust so it's no big deal if it's not good to pull :) I'm knee deep in the associated types stuff now, so I'll find out about the ICE soon enough probably :P

**Comment by sebcrozet** [comment]
I am currently working on a proper fix for `ncollide`. Since the ICE is not gone, I believe it might take a few days until I figure out how much associated types I can use without killing rustc.

**Comment by tinco** [comment]
Alright, it's weekend again and I have some time. If there's anything I can do to help you let me know :)

**Comment by tinco** [comment]
By the way did you see I put a vecmap implementation in this pull request? Not sure if that's a good idea, but they removed the old one and I couldn't figure out how to get it in so I just copied it and made it work.

**Comment by sebcrozet** [comment]
Yes, I've seen this. I don't know if we have any alternative. Could this copy/paste cause licensing issue ?

**Comment by tinco** [comment]
Well it's MIT licensed, I included the copyright notice in the file to make it clear that it's originally by the Rust team. MIT licenses are basically compatible with any other license. As long as you keep the copyright license in there it should be fine.

**Pull request closed without merging**
