### PR TITLE
Update for rustc 1.0 alpha

### PR DESCRIPTION
**Pull request by bfops**
I converted some of the closures over from the old syntax, but I got stuck at

    inspection/maybe_as_composite_shape.rs:43:44: 43:48 error: cannot convert to a trait object because trait `shape::composite_shape::CompositeShape` is not object-safe [E0038]
    inspection/maybe_as_composite_shape.rs:43                             mem::transmute(self as &CompositeShape<N, P, V, M>)
                                                                                         ^~~~
    inspection/maybe_as_composite_shape.rs:30:1: 49:3 note: in expansion of impl_composite_shape_repr!
    inspection/maybe_as_composite_shape.rs:51:1: 51:50 note: expansion site
    inspection/maybe_as_composite_shape.rs:43:44: 43:48 note: method `map_part_at` has generic type parameters
    inspection/maybe_as_composite_shape.rs:43                             mem::transmute(self as &CompositeShape<N, P, V, M>)
                                                                                         ^~~~
    inspection/maybe_as_composite_shape.rs:30:1: 49:3 note: in expansion of impl_composite_shape_repr!
    inspection/maybe_as_composite_shape.rs:51:1: 51:50 note: expansion site
    inspection/maybe_as_composite_shape.rs:43:44: 43:48 note: method `map_transformed_part_at` has generic type parameters
    inspection/maybe_as_composite_shape.rs:43                             mem::transmute(self as &CompositeShape<N, P, V, M>)

### CODE REVIEW

**Comment by sebcrozet** [comment]
That must be because you added generic type parameters to the mapping methods. I think replacing things like `fn map_part_at<F: Fn(&M, &Repr<N, P, V, M>)>(&self, uint, F);` by `fn map_part_at(&self, uint, &Fn(&M, &Repr<N, P, V, M>));` will do the trick for the `CompositeShape` and `SupportMap` traits.

**Comment by sebcrozet** [comment]
(And by `SupportMap` I meant `PreferedSamplingDirections`)

**Comment by bfops** [comment]
Oh that makes sense, I'll give that a shot.

**Comment by bfops** [comment]
@sebcrozet I'm adding commits to this PR for the breaking changes in the 1.0 alpha.

**Comment by bfops** [comment]
point/point_repr.rs:9:46: 9:63 error: `$arg0:ident` is followed by a sequence repetition, which is not allowed for `ident` fragments
    point/point_repr.rs:9     ($sself: ident.$name: ident($arg0: ident $(, $argN: ident)*)) => {
                                                                      ^~~~~~~~~~~~~~~~~
    ray/ray_repr.rs:9:46: 9:63 error: `$arg0:ident` is followed by a sequence repetition, which is not allowed for `ident` fragments
    ray/ray_repr.rs:9     ($sself: ident.$name: ident($arg0: ident $(, $argN: ident)*)) => {

**Comment by bfops** [comment]
Also `HashSet` has changed from `HashSet<T, Hasher>` to `HashSet<T, HashState>`. Is `DefaultState<SipHasher>` okay?

**Comment by bfops** [comment]
Actually it looks like we want to explicitly create state. Maybe `ncollide` needs its own `HashState` structure now?

**Comment by sebcrozet** [comment]
> I'm getting these errors in ncollide_procedural. I haven't thought much about it, but it seems like requiring a trailing comma on arguments to dispatch! might be the easiest solution. Thoughts?

I believe you can do ` ($sself: ident.$name: ident($($argN: ident),*)) => {` (note that the comma is now right before the star) instead, in order to avoid the trailing comma. That's what we did for sebcrozet/nalgebra#72.

> Actually it looks like we want to explicitly create state. Maybe ncollide needs its own HashState structure now?

All we want is to create a hasher with non-random keys so that the function using it has reproductible results. It looks like `DefaultState<SipHasher>` generates the hasher by calling `SipHasher::new_with_keys(0, 0)` which seems to be what we want.

**Comment by bfops** [comment]
> I believe you can do ($sself: ident.$name: ident($($argN: ident),*)) => { (note that the comma is now right before the star) instead, in order to avoid the trailing comma. That's what we did for sebcrozet/nalgebra#72.

Oh cool, done.

> All we want is to create a hasher with non-random keys so that the function using it has reproductible results. It looks like DefaultState<SipHasher> generates the hasher by calling SipHasher::new_with_keys(0, 0) which seems to be what we want.

Alright, I'll use `DefaultState<SipHasher>`. `ncollide_transformation/hacd.rs` has some explicit `SipHasher` creations with random seeds, is it okay to switch those to zero seeds?

    let mut uancestors = HashSet::with_hasher(SipHasher::new_with_keys(rng.gen(), rng.gen()));

**Comment by bfops** [comment]
Alright @sebcrozet I think I'm done, assuming `DefaultState` is fine for the hashers that were randomly-seeded before. I also haven't touched any of the tons of warnings, e.g. `int`/`uint` deprecation.

**Comment by sebcrozet** [comment]
> Alright, I'll use DefaultState<SipHasher>. ncollide_transformation/hacd.rs has some explicit > SipHasher creations with random seeds, is it okay to switch those to zero seeds?
>
> ```rust
> let mut uancestors = HashSet::with_hasher(SipHasher::new_with_keys(rng.gen(), rng.gen()));
```

Yes, using 0 keys should be OK here. In fact `rng` was created as `IsaacRng::new_unseeded()` which is a random number generator that will always output the same sequence of numbers.

Getting rid of the `#[old_impl_check]` won't be feasible before `nalgebra` uses associated types for its own trait. So it is OK to let them for now.

Thanks!

**Pull request merged**
